import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import "primereact/resources/themes/lara-light-cyan/theme.css";


export const metadata: Metadata = {
  title: "FlyToday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body
          className={`antialiased`}
        >
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
